<?php

namespace App\UssdTraits;

trait Menus {

    public function menu() {
        return '{"menu":[{"id":"root","response":"...",
		   "map":[{"key":"next","menu":"home"}],
		   "type":"static",
		   "action":"con"
		  },{"id":"home",		   
		   "response":"Reply with\n1. Account Balance\n2. Mini Statement\n3. Funds Transfer\n4. Airtime Purchase\n5. Mobile Money\n6. Utility Payment \n7. Change Pin\n8. Logout",
		   "map":[{"key":"1","menu":"BalanceAccounts"},{"key":"2","menu":"StatementAccounts"},{"key":"3","menu":"FTAccounts"},{"key":"4","menu":"MOBILEPROVIDER"},
		   {"key":"5","menu":"NewFT"},{"key":"6","menu":"utility"},{"key":"7","menu":"changePin"}],
		   "type":"dynamic",
		   "action":"con"
		  },{"id":"newAccount",
		   "response":"Please visit the banks you want to connect",
		   "map":[],  
		   "type":"static",
		   "link":"",
		   "action":"con"
		  },{"id":"nextMenu",
		   "response":"Reply with:\n1. PIN Change \n000. Logoff \n0.  Back",
		   "map":[{"key":"1","menu":"changePin"}],
		   "type":"dynamic",		   
		   "action":"con"
          },{"id":"fundst",
		   "response":"Reply with:\n1. Direct Transfer\n0. Home",
		   "map":[{"key":"1","menu":"iftFormAccount"}],
		   "type":"dynamic",		   
		   "action":"con"
          },{"id":"InterBankTransfer",
		   "response":"Select Bank:\n1. Centenary Bank",
		   "map":[{"key":"next","menu":"InterBankAccount"},{"key":"1","menu":"Centenary Bank"}],
		   "type":"dynamic",
           "name":"InterBankName",		   
		   "action":"con"
		  },{"id":"InterBankAccount", 
		   "response":"Enter Bank Account:",
		   "map":[{"key":"next","menu":"InterBankAmount"}],
		   "type":"form",
		   "name":"accountInterBank",
		   "action":"con"
          },{"id":"InterBankAmount", 
		   "response":"Enter Amount:",
		   "map":[{"key":"next","menu":"eftConfirm"}],
		   "type":"form",
		   "name":"AmountInterBank",
		   "action":"con"
          },{"id":"iftFormAccount",
		   "response":"Enter Account To Transfer To:",
           "map":[{"key":"next","menu":"validateFTAccount"}],
		   "type":"form",
           "name":"DirectAccount",		   
		   "action":"con"
		  },{"id":"iftFormAmountDirect",
		   "response":"Enter Amount To Transfer:",
		   "map":[{"key":"next","menu":"iftConfirm"}],
		   "type":"form",
           "name":"DirectAmount",		   
		   "action":"con"
		  },{"id":"utility",
		   "response":"1. Water\n2. KPLC Prepaid\n3. Pay TV\n0. Home",
		   "map":[{"key":"1","menu":"formWaterArea"},{"key":"2","menu":"umemePostpaid"},{"key":"3","menu":"paytv"},{"key":"5","menu":"KISOPTIONS"},
				  {"key":"6","menu":"URA"},{"key":"postMenu","menu":"utilityConfirm"}],
		   "type":"dynamic",
		   "link":"",
		   "action":"con"
		  },{"id":"KISOPTIONS",
		   "response":"1. PAY\n2. Retrieve Token\n0. Back",
		   "map":[{"key":"1","menu":"KIS"},
                  {"key":"2","menu":"KISValidate1"}],
		   "type":"dynamic",
		   "link":"",
		   "action":"con"
		  },{"id":"URA", 
		   "response":"Enter ESlip Number:",
		   "map":[{"key":"next","menu":"ValidateURA"},{"key":"postMenu","menu":"URAPinConfirm"}],
		   "type":"form",
		   "name":"acURA",
		   "action":"con"
		  },{"id":"KCCA", 
		   "response":"Enter KCCA Reference Number:",
		   "map":[{"key":"next","menu":"ValidateKCCA"},{"key":"postMenu","menu":"KCCAPinConfirm"}],
		   "type":"form",
		   "name":"acKCCA",
		   "action":"con"
		  },{"id":"Startimes", 
		   "response":"Enter Account Number:",
		   "map":[{"key":"next","menu":"startimesValidate"}],
		   "type":"form",
		   "name":"acStartimes",
		   "action":"con"
		  },{"id":"StarTimesformAmount",
		   "response":"Enter amount:",
		   "map":[{"key":"next","menu":"STVAccounts"}],
		   "type":"form",
		   "link":"",
           "name":"StarTimesformAmount",
		   "action":"con"
          },{"id":"formWaterArea","response":"Choose Area:\n1:Nairobi West\n2:Eastleigh\n3:Uthiru\n4:Komarock\n5:Umoja\n6:Dagorreti\n7:Kasarani\n8:Ruaka\n9:Others\n0. Home",
		   "map":[{"key":"1","menu":"NATWATERUG"},{"key":"2","menu":"NATWATERUG"},{"key":"3","menu":"NATWATERUG"},{"key":"4","menu":"NATWATERUG"},
                     {"key":"5","menu":"NATWATERUG"},{"key":"6","menu":"NATWATERUG"},{"key":"7","menu":"NATWATERUG"},{"key":"8","menu":"NATWATERUG"},{"key":"9","menu":"NATWATERUG"}],
		   "type":"dynamic",
		   "name":"area",
		   "action":"con"
		  },{"id":"KIS", 
		   "response":"Enter Meter number:",
		   "map":[{"key":"next","menu":"KisWaterValidate"},{"key":"postMenu","menu":"KISConfirm"}],
		   "type":"form",
		   "name":"acKIS",
		   "action":"con"
		  },{"id":"KISformAmount",
		   "response":"Enter amount:",
		   "map":[{"key":"next","menu":"KisWaterAccounts"}],
		   "type":"form",
		   "link":"",
           "name":"kisformAmount",
		   "action":"con"
          },{"id":"NATWATERUG", 
		   "response":"Enter your water account number:",
		   "map":[{"key":"next","menu":"waterValidate"}],
		   "type":"form",
		   "name":"ac",
		   "action":"con"
		  },{"id":"WaterformAmount",
		   "response":"Enter amount:",
		   "map":[{"key":"next","menu":"WaterAccounts"}],
		   "type":"form",
		   "link":"",
           "name":"WaterformAmount",
		   "action":"con"
          },{"id":"formAmount",
		   "response":"Enter amount:",
		   "map":[{"key":"next","menu":"payments"}],
		   "type":"form",
		   "link":"",
           "name":"formAmount",
		   "action":"con"
          },{"id":"umemePostpaid", 
		   "response":"Enter your Umeme account number:",
		   "map":[{"key":"next","menu":"umemePostpaidValidate"}],
		   "type":"form",
		   "name":"umemeAccount",
		   "action":"con"
		  },{"id":"umemePostpaidAmount",
		   "response":"Enter amount:",
		   "map":[{"key":"next","menu":"UmemePostpaidAccounts"}],
		   "type":"form",
           "name":"formAmount",
		   "action":"con"
          },{"id":"umemeYaka", 
		   "response":"Enter your Umeme account number:",
		   "map":[{"key":"next","menu":"umemeYakaValidate"}],
		   "type":"form",
		   "name":"umemeAccount",
		   "action":"con"
          },{"id":"umemeYakaAmount",
		   "response":"Enter amount:",
		   "map":[{"key":"next","menu":"UmemeYakaAccounts"}],
		   "type":"form",
           "name":"formAmount",
		   "action":"con"
          },{"id":"paytv",
		   "response":"1. DSTV\n2. GOTV\n3. DSTVPVR\n4. Startimes\n0. Home",
		   "map":[{"key":"1","menu":"dstvPackage"},{"key":"2","menu":"gotvPackage"},{"key":"3","menu":"dstvpvrPackage"},{"key":"4","menu":"Startimes"}],
		   "type":"dynamic",
		   "link":"",
		   "action":"con"
		  },{"id":"dstvPackage","response":"Choose Package:\n1. Premium 219,000 ugx\n2. CompactPlus 129,000 ugx\n3. Compact 79,000 ugx\n4. Family 49,000 ugx\n5. Access 33,000 ugx\n0. Home",
		   "map":[{"key":"1","menu":"dstvPeriod"},{"key":"2","menu":"dstvPeriod"},{"key":"3","menu":"dstvPeriod"},{"key":"4","menu":"dstvPeriod"},{"key":"5","menu":"dstvPeriod"}],
		   "type":"dynamic",
		   "name":"dstvPackage",
		   "action":"con"
            },{"id":"gotvPackage","response":"Choose Package:\n1. GOtvPlus 26000 ugx\n2. GOtvValue 16000 ugx\n3. GOtvLite1 11000 ugx\n4. GOtvLite3 25000 ugx\n5. GOtvLite12 70000 ugx \n6. GotvMax 39000\n0. Back",
		   "map":[{"key":"1","menu":"dstvPeriod"},{"key":"2","menu":"dstvPeriod"},{"key":"3","menu":"dstvPeriod"},{"key":"4","menu":"dstvPeriod"},{"key":"5","menu":"dstvPeriod"},{"key":"6","menu":"dstvPeriod"}],
		   "type":"dynamic",
		   "name":"dstvPackage",
		   "action":"con"
            },{"id":"dstvpvrPackage","response":"Choose Package:\n1. HDPVR 41250 ugx\n2. SDPVR 41250 ugx\n3. Dual View 41250 ugx\n0. Home",
		   "map":[{"key":"1","menu":"dstvPeriod"},{"key":"2","menu":"dstvPeriod"},{"key":"3","menu":"dstvPeriod"}],
		   "type":"dynamic",
		   "name":"dstvPackage",
		   "action":"con"
            },{"id":"dstvPeriod","response":"Choose Period:\n1. Monthly\n2. Yearly\n0. Back",
		   "map":[{"key":"next","menu":"dstvAccountType"},{"key":"1","menu":"Monthly"},{"key":"2","menu":"Yearly"}],
		   "type":"dynamic",
		   "name":"dstvPeriod",
		   "action":"con"
            },{"id":"dstvAccountType","response":"Select the account number type:\n1. CustomerNumber\n2. SmartCard\n0. Back",
		   "map":[{"key":"next","menu":"dstvUG"},{"key":"1","menu":"CustomerNumber"},{"key":"2","menu":"SmartCard"}],
		   "type":"dynamic",
		   "name":"dstvAccountType",
		   "action":"con"
            },{"id":"dstvUG", 
		   "response":"Enter your smart card number or DSTV account number:",
		   "map":[{"key":"next","menu":"dstvValidate"}],
		   "type":"form",
		   "name":"dstvAccount",
		   "action":"con"
		  },{"id":"NewFT",
		   "response":"1. Send To Airtel Money\n2. Send To MTN Mobile Money\n0. Home",
		   "map":[{"key":"1","menu":"MobileMoneyFT"},{"key":"2","menu":"MobileMoneyFT"}],
		   "type":"dynamic",		   
		   "action":"con"
		  },{"id":"MobileMoneyFT",
		   "response":"1. Load My Phone\n2. Load other Phone\n0. Home",
		   "map":[{"key":"1","menu":"formAmountMM"},{"key":"2","menu":"formAccountMobile"}],
		   "type":"dynamic",		   
		   "action":"con"
		  },{"id":"formAmountMM",
		   "response":"Enter amount:",
		   "map":[{"key":"next","menu":"MobileMoneyAccounts"},{"key":"postMenu","menu":"MMConfirm"}],
		   "type":"form",
		   "link":"",
           "name":"acamountMM",
		   "action":"con"
          },{"id":"formAccountMobile", 
		   "response":"Enter mobile number:",
		   "map":[{"key":"next","menu":"formAmountMM"}],
		   "type":"form",
		   "name":"ac",
		   "action":"con"
		  },{"id":"MOBILEPROVIDER",
		   "response":"\n1 My Phone\n2 Other Phone",
		   "map":[{"key":"1","menu":"PinlessAirtimeAmount"},{"key":"2","menu":"pinlessMsisdn2"},{"key":"postMenu","menu":"airtimeConfirm"}],
		   "type":"dynamic",		   
		   "action":"con"
		  },{"id":"PinlessAirtimeAmount",
		   "response":"Reply with Airtime amount:",
		   "map":[{"key":"next","menu":"AirtimeOwnAccounts"}],
		   "type":"form",
           "name":"PinlessAirtimeAmount",		   
		   "action":"con"
		  },{"id":"pinlessMsisdn2",
		   "response":"Reply with number to load airtime:",
		   "map":[{"key":"next","menu":"PinlessAirtimeAmount"}],
		   "type":"form",
           "name":"pinlessMsisdn2",		   
		   "action":"con"
		  },{"id":"changePin",
		   "response":"Enter your old pin:",
		   "map":[{"key":"next","menu":"newPin1"}],
		   "type":"form",
           "name":"oldPin",		   
		   "action":"con"
		  },{"id":"newPin1",
		   "response":"Enter a new pin:",
		   "map":[{"key":"next","menu":"newPin2"}],
		   "type":"form",
           "name":"newPin1",		   
		   "action":"con"
		  },{"id":"newPin2",
		   "response":"Renter your new pin:",
		   "map":[{"key":"next","menu":"pinChangeConfirmNew"}],
		   "type":"form",
           "name":"newPin2",		   
		   "action":"con"
		  },{"id":"newPin11",
		   "response":"Enter a new pin:",
		   "map":[{"key":"next","menu":"newPin22"}],
		   "type":"form",
           "name":"newPin1",		   
		   "action":"con"
		  },{"id":"newPin22",
		   "response":"Renter your new pin:",
		   "map":[{"key":"next","menu":"forcedPinChangeConfirm"}],
		   "type":"form",
           "name":"newPin2",		   
		   "action":"con"
		  },{"id":"subregister",
		   "response":"go to register",
		   "map":[{"key":"next","menu":"register"}],
		   "type":"static",
		   "action":"con"
		  },{"id":"register",
		   "response":"Please reply with 1 to register",
		   "map":[{"key":"next","menu":"formFName"},{"key":"postMenu","menu":"registerConfirm"}],
		   "type":"static",
		   "action":"con"
		  },{"id":"formFName",
		   "response":"Enter your first name:",
		   "map":[{"key":"next","menu":"formLName"}],
		   "type":"form",		   
		   "action":"con"
		  },{"id":"formLName",
		   "response":"Enter your last name:",
		   "map":[{"key":"next","menu":"formIDNUM"}],
		   "type":"form",		   
		   "action":"con"
		  },{"id":"formIDNUM",
		   "response":"Enter ID number:",
		   "map":[{"key":"next","menu":"formPin"}],
		   "type":"form",		   
		   "action":"con"
		  },{"id":"formPin",
		   "response":"Enter a new pin:",
		   "map":[{"key":"next","menu":"registerConfirm"}],
		   "type":"form",		   
		   "action":"con"
		  },{"id":"registerEnd",
		   "response":"Welcome to ELMA. You will receive a confirmation SMS shortly",
		   "map":[{"key":"next","menu":"home"}],
		   "type":"static",		   
		   "action":"end"
		  },{"id":"formAccount", 
		   "response":"Enter your Account number:",
		   "map":[{"key":"next","menu":"formAmount"}],
		   "type":"form",
		   "name":"acmsisdn",
		   "action":"con"
		  },{"id":"formMsisdn",
		   "response":"Enter phone number to send money to",
		   "map":[{"key":"next","menu":"formAmount"}],
		   "type":"form",
		   "link":"",
		   "action":"con"
		  },{"id":"Success",
		   "response":"Transaction completed successfully",
		   "map":[{"key":"next","menu":"home"}],
		   "type":"static",
		   "link":"",
		   "action":"end"
		  },{"id":"iftFormAmount",
		   "response":"Enter Amount To Transfer:",
		   "map":[{"key":"next","menu":"accountIFTConfirm"},{"key":"header","menu":"account"}],
		   "type":"form",		   
		   "action":"con"
		  },{"id":"eftFormAccount",
		   "response":"Enter Account Number to transfer to:",
		   "map":[{"key":"next","menu":"eftFormAmount"},{"key":"header","menu":"account"}],
		   "type":"form",		   
		   "action":"con"
		  },{"id":"eftFormAmount",
		   "response":"Enter Amount to transfer:",
		   "map":[{"key":"next","menu":"eftConfirm"},{"key":"header","menu":"account"}],
		   "type":"form",		   
		   "action":"con"
		  },{"id":"eftConfirm_",
		   "response":"Send :eftFormAmount amount to :eftFormAccount\n Reply with:\n1. Accept\n2. Cancel\n0. Home",
		   "map":[{"key":"header","menu":"account"},
                  {"key":":eftFormAmount","menu":"eftFormAmount"},{"key":":eftFormAccount","menu":"eftFormAccount"}],
		   "type":"confirm",
           "category":"EFT",
           "categoryId":"M-003001005", 		   
		   "action":"con"
		  },{"id":"accountId",		   
		   "map":[{"key":"DSTV","menu":"007001001"},{"key":"ORANGE","menu":"256003001001"},
                  {"key":"UMEME","menu":"007001002"},{"key":"WATER","menu":"007001003"},
                  {"key":"MTN","menu":"256003001001"},{"key":"UTL","menu":"256003001001"},
                  {"key":"WARID","menu":"256003001001"},{"key":"AIRTEL","menu":"256003001001"}],
		   "type":"static"
            },{"id":"LoanKUSimu",
		   "response":"Select Option:\n1. Apply for Loan\n0. Home",
		   "map":[{"key":"1","menu":"LoanTerm"}],
		   "type":"dynamic",
		   "action":"con"
          },{"id":"LoanTerm","response":"Select Term:\n1. One Month\n2. Two Months\n3. Three Months\n0. Home",
		   "map":[{"key":"1","menu":"LoanAmount"},{"key":"2","menu":"LoanAmount"},{"key":"3","menu":"LoanAmount"}],
		   "type":"dynamic",
		   "action":"con"
            },{"id":"LoanAmount", 
		   "response":"Enter Loan Amount(Between 50,000 - 1,000,000):",
		   "map":[{"key":"next","menu":"PhoneLoanAccount"}],
		   "type":"form",
		   "action":"con"
		  },{"id":"logout_",
		   "response":"You have successfully logged out, thank you. Finance Trust Bank.",
		   "map":[{"key":"next","menu":"home"}],
		   "type":"static",
		   "link":"",
		   "action":"end"
		  },{"id":"mmerror",
		   "response":"Sorry, the system is currently off, please try again later.",
		   "map":[{"key":"next","menu":"home"}],
		   "type":"static",
		   "link":"",
		   "action":"end"
		  },{"id":"end",
		   "response":"Your request is being processed. You will receive a confirmation SMS shortly.",
		   "map":[{"key":"next","menu":"home"}],
		   "type":"static",
		   "link":"",
		   "action":"end"
		  },{"id":"AgencyWithdraw", 
		   "response":"Enter Amount:",
		   "map":[{"key":"next","menu":"AgentAccounts"},{"key":"postMenu","menu":"AgencyConfirm"}],
		   "type":"form",
		   "name":"AmountAgency",
		   "action":"con"
          },{"id":"pinend",
		   "response":"Your PIN has been changed successfully. Please exit and login again with the new PIN.",
		   "map":[{"key":"next","menu":"home"}],
		   "type":"static",
		   "link":"",
		   "action":"end"
		  },{"id":"pinenderror",
		   "response":"Pin change encountered an error. Please try again later.",
		   "map":[{"key":"next","menu":"home"}],
		   "type":"static",
		   "link":"",
		   "action":"end"
		  },{"id":"cancel",
		   "response":"Transaction canceled, Reply with 0 for home menu",
		   "map":[{"key":"next","menu":"home"}],
		   "type":"static",
		   "link":"",
		   "action":"con"
		  }]}';
    }

}
